### ISSUE TITLE
Remaining amount should be transferred back to the msg.sender instead to the first receiver.

### ISSUE THREAD

**Issue by supernovahs** [Avelous/Eth-Splitter#8]
splitequalEth splits equal amount to all the receivers. Any remaining amount left  due to division is sent to the first receiver . 

https://github.com/Avelous/Eth-Splitter/blob/095194467bea81f9e030edf0e854fc45a54ee276/packages/hardhat/contracts/Splitter.sol#L79-L82

We are not sending it back to the sender as the amount will be very nominal  ?
Wanted to know your thoughts
@Avelous @viraj124

**Comment by viraj124** [comment]
My thought was in context it didn't seem out of place or completely wrong I was okay in terms of the current way but def we can return the remaining to the funder too check with @Avelous on tg

**Comment by cacosta88** [comment]
Original thought is that since dust is relatively immaterial could be sent to one of the recipients. If it's sent back to the sender, it's an additional eth transfer (there is an argument to avoid additional gas on a little bit of dust). It is cheaper to just adjust the amount of one of the recipients.
